//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NavigationA.proto
// Note: requires additional types generated from: Math.proto
namespace com.QH.QPGame.Fishing
{
	using Pak;

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NavigationA")]
  public partial class NavigationA : global::ProtoBuf.IExtensible
  {
    public NavigationA() {}
    
    private readonly global::System.Collections.Generic.List<Vector3> _frame = new global::System.Collections.Generic.List<Vector3>();
    [global::ProtoBuf.ProtoMember(1, Name=@"frame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Vector3> frame
    {
      get { return _frame; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}