//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NavigHead.proto
namespace com.QH.QPGame.Fishing
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NavigHead")]
  public partial class NavigHead : global::ProtoBuf.IExtensible
  {
    public NavigHead() {}
    
    private string _type = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _idStr = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"idStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string idStr
    {
      get { return _idStr; }
      set { _idStr = value; }
    }
    private uint _idUInt = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"idUInt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint idUInt
    {
      get { return _idUInt; }
      set { _idUInt = value; }
    }
    private float _cycleTime = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cycleTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float cycleTime
    {
      get { return _cycleTime; }
      set { _cycleTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}