// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;

namespace com.QH.QPGame.Services.Utility
{
		public class ObjectByteConvertor
		{
			public static Byte[] ObjectToBytes (Object obj)
			{ 
				BinaryFormatter formatter = new BinaryFormatter (); 
				MemoryStream stream = new MemoryStream (); 
				formatter.Serialize (stream, obj); 
				stream.Flush ();
				byte[] theBytes = stream.ToArray ();
				stream.Close ();
				return theBytes; 
			}

			public object BytesToObject (byte[] b)
			{ 
				BinaryFormatter formatter = new BinaryFormatter (); 
				MemoryStream rems = new MemoryStream (b); 
				object obj = formatter.Deserialize (rems); 
				rems.Close ();
				return obj;
			} 
		}
}

