// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Runtime.InteropServices;

namespace com.QH.QPGame.Services
{

	public static class SizeOfC
	{
		public const  int WORD = 2; // unsigned short
		public const  int DWORD = 4; // unsigned int
		public const  int BYTE = 1; // unsigned char
		public const  int SHORT = 2; // short    
		public const  int TCHAR = 1; // char
		public const  int LONG = 4; // long
		public const  int LONGLONG = 8; // long long
		public const  int ULONG = 4; // unsigned long
		public const  int DATE = 8; // double
		public const  int UCHAR = 1; // unsigned char
		public const  int UINT = 4; // unsigned int
		public const  int INT = 4; // int
		public const  int SCORE = LONGLONG; // long long
		public const  int DOUBLE = LONGLONG; // int
		public const  int COLORREF = 4;
		public const  int SYSTEMTIME_SIZE = 8 * WORD;

	    public static int GetSize<T>()
	    {
	        Type t = typeof (T);
	        int size = 0;

	        if (t.IsValueType)
	        {
	            if (t.IsGenericType)
	            {
	                size = Marshal.SizeOf(default(T));
	            }
	            else
	            {
	                size = Marshal.SizeOf(t);
	            }
	        }
	        else
	        {
	            size = IntPtr.Size;
	        }

	        return size;
	    }
	}

	[System.Serializable]
	[StructLayout(LayoutKind.Sequential, Pack = 1)]
	public struct SYSTEMTIME
	{
		public UInt16 wYear;
		public UInt16 wMonth;
		public UInt16 wDayOfWeek;
		public UInt16 wDay;
		public UInt16 wHour;
		public UInt16 wMinute;
		public UInt16 wSecond;
		public UInt16 wMilliseconds;
	}

}

